/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:c20a9c4c-053b-4fb7-8237-e2e4ad83c936",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_hF7x58cwP",
    "aws_user_pools_web_client_id": "1m8jf8aaebfi5mh8l6vi3tm4ce",
    "oauth": {}
};


export default awsmobile;
